# Production
[context.production.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service.herokuapp.com/api"
GATSBY_SMART_MENU_URL = "https://web-menu-prod.netlify.app"

# PR Previews
[context.deploy-preview.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service-testing.herokuapp.com/api"
GATSBY_SMART_MENU_URL = "https://develop-web-menu-prod.netlify.app"

# Staging
[context.master.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service-staging.herokuapp.com/api"
GATSBY_SMART_MENU_URL = "https://web-menu-staging.netlify.app"

# Testing
[context.develop.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service-testing.herokuapp.com/api"
GATSBY_SMART_MENU_URL = "https://develop--web-menu-prod.netlify.app"
