[context.production.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service.herokuapp.com/api"

[context.deploy-preview.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service-staging.herokuapp.com/api"

[context.branch-deploy.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service-staging.herokuapp.com/api"