# Production
[context.production.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service.herokuapp.com/api"
GATSBY_SMART_MENU_URL = "https://nomi-smart-menu.netlify.app"

# PR Previews
[context.deploy-preview.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service-testing.herokuapp.com/api"
GATSBY_SMART_MENU_URL = "https://develop-nomi-smart-menu.netlify.app"

# Staging
[context.master.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service-staging.herokuapp.com/api"
GATSBY_SMART_MENU_URL = "https://master--nomi-smart-menu.netlify.app"

# Testing
[context.develop.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service-testing.herokuapp.com/api"
GATSBY_SMART_MENU_URL = "https://develop--nomi-smart-menu.netlify.app"
